language: node_js
node_js:
- '8'
cache: yarn
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn build
- yarn test
- yarn lint
before_deploy:
- npm i -g firebase-tools
deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT
  on:
    branch: master
