language: node_js
node_js:
- '8'
script:
- yarn build
- yarn test
- yarn lint
deploy:
  provider: firebase
  on:
    branch: master
  token:
    secure: TckaC4uDgaOuxZBvRRWxya7L5mNyxHK0NGMF6joL1VYZZVNvaH3fAIBpmADVz1XoWBlL7WNOVauBY/yNp5+owwUnCk0fu4R5/v5FcXSWV52J83BeLpzXBb/5jnZ6hlg51iIVGaVseQ+r10j8Y/0f59HoOkW5WIgARe36EdfNN4I=
  project: $FIREBASE_PROJECT
