description = "私の運営しているウェブサイトの一覧"

[[websites]]
id = "201203231122"
name = "そんなこと覚えてない"
url = "http://blog.eiel.info"
description = "技術系のメモを残しているブログです。"

[[websites]]
id = "201203290000"
name = "日常と勉強会と広島と。"
url = "http://eielh-life.tumblr.com/"
description = "勉強会に参加したことや広島での出来事を友人という設定で書いている日記です。"
