title = "iOSアプリケーション"
description = "作成したiOSのアプリケーションです。iTunesからダウンロードできます。"

[[items]]
name = "縦置"
description = "文字を表示するだけのアプリです。"
url = "http://itunes.apple.com/jp/app/id390444064?mt=8"

[[items]]
name = "カウントしNite"
description = "登録したイベントのカウントダウンをするアプリです。"
url = "http://itunes.apple.com/jp/app/id399605073?mt=8"

[[items]]
name = "RapidMail"
description = "あらかじめ作成したテンプレートを元にメールを作成するアプリです。"
url = "http://itunes.apple.com/jp/app/rapidmail/id493436340?mt=8"
android_url = "https://market.android.com/details?id=net.sugarspot.rapidmail"
