[[services]]
name = "GitHub"
url = "https://github.com/eiel"

[[services]]
name = "Twitter"
url = "https://twitter.com/eielh"

[[services]]
name = "Qiita"
url = "http://qiita.com/eielh"

[[services]]
name = "Tumblr"
url = "http://eielh.tumblr.com/"

[[services]]
name = "Facebook"
url = "https://www.facebook.com/eielh"

[[services]]
name = "Google+"
url = "https://plus.google.com/+himuratomohiko"

[[services]]
name = "Flicr"
url = "https://www.flickr.com/photos/43922152@N04/"

[[services]]
name = "foursqure"
url = "https://ja.foursquare.com/eielh"

[[services]]
name = "YouTube"
url = "https://www.youtube.com/user/eielh/videos"

[[services]]
name = "BitBucket"
url = "https://bitbucket.org/eiel"
